name: LadiesOfSteampunk
favicon: null
layout_spectrum: 0.48128
typography_spectrum: 0.80972
title: Beautiful Ladies - Designs - Steampunk
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ff0000'
    - '#ffff00'
    - '#ff8000'
    - '#ffffff'
  brandStrength: 0.75
  lightness: 0.9544903510250151
  saturation: 0.5625
  rhythmicContrast: 0.9303563244175166
purpose: []
