name: LadiesOfSteampunk
favicon: null
layout_spectrum: 0.82955
typography_spectrum: 0.7786961693782359
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.4034263789653778
  lightness: 0.9544903510250151
  saturation: 0.28239213838241994
  rhythmicContrast: 0.9303563244175166
purpose: []
